version: '2'
services:

  # https://github.com/tiangolo/uwsgi-nginx-flask-docker/tree/master/example-flask-package-python3.6
  app:
    depends_on:
      - db
      - adminer
    build:
      context: .
      dockerfile: ./Dockerfile
    image: flask-app
    environment:
      - FLASK_APP=app/main.py
      - 'RUN=flask run --host=0.0.0.0 --port=80'
    env_file:
      - .env.flask
      - .env.mysql
    volumes:
      - ./app:/app
    ports:
      - 5000:80

  db:
    image: mysql:5.7
    env_file: .env.mysql
    volumes:
      - ./.mysql:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d
      - ./mysql.cnf:/etc/mysql/conf.d/mysql.cnf

  adminer:
    depends_on:
      - db
    image: adminer
    ports:
      - 8080:8080
