version: '3'

services:
  api:
    build:
      context: ./WebAPI
      dockerfile: Dockerfile
    image: api
    container_name: web-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - '3000:80'
