version: '2'
services:

  app:
    depends_on:
      - db
    build:
      context: .
      dockerfile: ./Dockerfile
    image: node-app
    env_file: .env
    volumes:
      - .:/usr/src/app
    ports:
      - 3000:3000
    command: npm start

  debug:
    depends_on:
      - db
    build:
      context: .
      dockerfile: ./Dockerfile
    image: node-app
    env_file: .env
    volumes:
      - .:/usr/src/app
    ports:
      - 3000:3000
      - 9229:9229
    command: npm run debug

  shell:
    depends_on:
      - db
    build:
      context: .
      dockerfile: ./Dockerfile
    image: node-app
    env_file: .env
    volumes:
      - .:/usr/src/app
    command: bash

  db:
    image: sath89/oracle-12c
    environment:
      - WEB_CONSOLE=false
      # uncomment to run import on every startup
      # - IMPORT_FROM_VOLUME=true
    volumes:
      - ./db-data:/u01/app/oracle
      - ./db-init:/docker-entrypoint-initdb.d
    ports:
      - 1521:1521
